apiVersion: v1
kind: Pod
metadata:
  name: programmingonmars
  labels:
    app: programmingonmars
spec:
  containers:
    - name: programmingonmars-container
      image: andrelucastic/demo:1.0
      ports:
        - containerPort: 80
